services:
  star-wars-for-dummies:
    image: star-wars
    container_name: star-wars

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    env_file:
      - .env

