# Description: Dockerfile for the python app

# Use the official Python image as the base image
FROM python

# Set the working directory in the container
WORKDIR /bmi-calculator

# Copy all the files from the current directory to the container
COPY . .

# Run the app when the container launches
CMD ["python", "bmi.py"]
