services:
  feedback-app:
    image: feedback-app
    container_name: feedback-app

    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ./:/feedbackApp                      # Bind mount the current directory to the /feedbackApp directory in the container
      - /feedbackApp/node_modules            # Anonymous volume to persist node_modules

    ports:
      - "80:80"

    env_file:
      - .env

