services:
  goals-app:
    image: goals-app:compose
    container_name: goals-app

    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ./:/goals-app
      - /goals-app/node_modules

    env_file:
      - .env

    ports:
    - "3000:${PORT}"

